import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import { Kanit } from "next/font/google";
import BootstrapClient from '@components/app/components/BootstrapClient';

import Header from '@components/app/components/Header';
import Footer from '@components/app/components/Footer';

const kanit = Kanit({ subsets: ["latin"], weight: "500" });

export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={kanit.className}>
                <Header />
                {children}
                <Footer />
                <BootstrapClient />
            </body>
        </html>
    );
}
